press d to toggle all analysis off.
sanderland/katrain pull request #352
Opened 2021-02-02 13:12 UTC by xiaoyifang

issue https://github.com/sanderland/katrain/issues/330
does not sure if there is a more better solution.haven't program in python for years.

2021-02-02 13:19 UTC, sanderland commented
please target the next release, not master. 
I think this conflates two features and should be split up:

* reset analysis to base state (whatever key is next on the middle row)
* stop current analysis (esc?, keep in mind to also turn off continuous analysis)

2021-02-03 06:56 UTC, xiaoyifang commented
does the feature "reset analysis to base state"  contains the feature "stop current analysis "?

2021-02-03 09:39 UTC, sanderland commented
> does the feature "reset analysis to base state" contains the feature "stop current analysis "?

It is hard to determine what queries belong to the current analysis, so I wouldn't think so. You're right that there's some annoying edge cases though.

2021-02-03 13:50 UTC, xiaoyifang commented
the branch contribute  can not start ,when run ,it will throw an exception 
"ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 3221225501ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 3221225501
"

2021-02-03 14:24 UTC, xiaoyifang commented
maybe use new field in GameNode such as ,query_keys to store all the current analysis queryid.
i want to bind the clear function to a key ,any recommend keys .

2021-02-03 15:01 UTC, sanderland commented
> maybe use new field in GameNode such as ,query_keys to store all the current analysis queryid.
maybe it'd be cleaner to store an optional extra field in the tuple in queries. then terminate queries can take an optional node and either terminate queries for that node, or all.

> i want to bind the clear function to a key ,any recommend keys .

h?

2021-02-05 09:15 UTC, sanderland commented
just use the request review feature when you're ready @xiaoyifang

2021-02-05 10:31 UTC, xiaoyifang commented
> just use the request review feature when you're ready @xiaoyifang

I'm ready,   but does not know how to  start request review.

2021-02-05 10:35 UTC, sanderland commented
![image](https://user-images.githubusercontent.com/48946947/107022913-3a94e280-67a6-11eb-8c05-5052fcee7633.png)

2021-02-05 10:37 UTC, sanderland commented on katrain/core/engine.py
> +                callback, error_callback, start_time, next_move, cn = self.queries.pop(query_id, None)
cn -> node

2021-02-05 10:40 UTC, sanderland commented on katrain/core/game.py
> +        engine.terminate_current_queries()
terminate_queries(cn)

2021-02-05 10:41 UTC, sanderland commented on katrain/core/engine.py
> +        self.analysis_node = analysis_node
remove, the engine may be working on any number of nodes and the last query is not necessarily the currnet node

2021-02-05 10:41 UTC, sanderland commented on katrain/core/engine.py
> +        self.send_query(query, callback, error_callback, next_move, current_analysis)
pass analysis node instead

2021-02-05 10:42 UTC, sanderland requested changes
Have another look at the logic, keeping in mind that the engine is highly parallel

2021-02-06 10:52 UTC, sanderland commented on katrain/core/engine.py
> +                if current_node is not None and current_node == node:
current_node is None or

2021-02-06 10:53 UTC, sanderland commented on katrain/core/engine.py
> +                query, callback, error_callback, next_move, current_node = self.write_queue.get(block=True, timeout=0.1)
just `node`

2021-02-06 10:54 UTC, sanderland commented on katrain/core/engine.py
> +    def send_query(self, query, callback, error_callback, next_move=None, current_node=None):
`node`

2021-02-06 10:55 UTC, sanderland requested changes
one tiny thing, will merge later when I have the time to test.

2021-02-06 17:24 UTC, sanderland commented
Thank you for your contribution @xiaoyifang

2021-02-06 17:25 UTC, merged

2021-02-06 18:03 UTC, sanderland commented
gui + some renaming in 5011d07