1.9 dev
sanderland/katrain pull request #411
Opened 2021-04-12 13:01 UTC by sanderland

2021-05-10 08:17 UTC, sanderland commented
@Harleqin @Tony-Liou @kaorahi @Dontbtme @Satoshi-Yoda this should be ready for translation now.

![image](https://user-images.githubusercontent.com/48946947/117625911-d273e500-b176-11eb-8928-03494e2046a4.png)
![image](https://user-images.githubusercontent.com/48946947/117627876-db65b600-b178-11eb-8e59-0785431c2099.png)

2021-05-11 12:17 UTC, kaorahi commented
a9aa121 doesn't fix the font problem.

~~~
$ git show --quiet --pretty=format:'%h%d'
8c29b06 (HEAD -> 1.9, upstream/1.9)
$ git diff --stat
 katrain/i18n/locales/jp/LC_MESSAGES/katrain.mo | Bin 21300 -> 21414 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)
~~~
![font](https://user-images.githubusercontent.com/38910552/117813527-262d1e00-b29e-11eb-9693-461d102ef5a3.png)

2021-05-11 12:21 UTC, sanderland commented
9d1c500 does

2021-05-11 12:29 UTC, kaorahi commented
yes. fixed in 9d1c500. thx!

2021-05-13 02:11 UTC, Tony-Liou requested changes
Traditional Chinese is used as writing system rather than Simplified in Taiwan.

2021-05-13 02:11 UTC, Tony-Liou commented on katrain/i18n/locales/tw/LC_MESSAGES/katrain.po
> +msgstr "僅分析错误操作"
Simplified to Traditional
`错误` -> `錯誤`

2021-05-13 07:29 UTC, sanderland commented on katrain/i18n/locales/tw/LC_MESSAGES/katrain.po
> +msgstr "僅分析错误操作"
@chingyulin is Taiwanese, you can fight here and agree on the best translation ;)

2021-05-13 07:33 UTC, chingyulin commented on katrain/i18n/locales/tw/LC_MESSAGES/katrain.po
> +msgstr "僅分析错误操作"
agree with @Tony-Liou on 錯誤, my mistake.  `僅分析錯誤操作`

2021-06-28 14:59 UTC, merged